#!/usr/bin/python3
import sys
"""RSA Factoring Challenge"""

def factorizer(value):
    if(value > 2):
        for i in range(2, value):
            if(value % i == 0):
                print("{:.0f}={:.0f}*{:.0f}".format(value, value/i, i))
                break
try:
    with open(sys.argv[1]) as file:
        line = file.readline()

        while line != "":
            value = int(line.split('\n')[0])
            factorizer(value)
            line = file.readline()
except:
    pass
