#!/usr/bin/python2
import sys
"""RSA Factoring Challenge"""

try:
    with open(sys.argv[1], "r") as file_read:
        contents = file_read.readlines()
    for content in contents:
        n = int(content)
    
    if(n > 1):   
        for i in range(2, int(n**0.5) + 1):
            if not n % i:
                print("{}={}*{}".format(n,n//i,i))
                break
        else:
            print("{}={}*{}".format(n,n,1))

except (FileNotFoundError, ValueError):
    pass
